aliases = [ "es6", "es2015" ]
dependencies = [
	"_ESAbstract.CreateMethodProperty",
	"_ESAbstract.HasProperty",
	"_ESAbstract.ToInteger"
]
license = "MIT"
spec = "https://tc39.github.io/ecma262/#sec-array.prototype.copywithin"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/copyWithin"

[browsers]
android = "*"
chrome = "<45"
firefox = "<32"
firefox_mob = "<32"
ie = "*"
opera = "<32"
op_mob = "<32"
safari = "<9.0"
ios_saf = "<9.0"
samsung_mob = "<5.0"
