dependencies = [
	"_ArrayIterator",
	"Symbol.iterator",
	"DOMTokenList",
	"Element.prototype.classList"
]

license = "MIT"
spec = "https://dom.spec.whatwg.org/#domtokenlist"

[browsers]
bb = "10 - *"
chrome = "<50"
edge = "<16"
edge_mob = "<16"
firefox = "<50"
firefox_mob = "<50"
ie = ">=9"
ie_mob = ">=9"
opera = "<50"
op_mob = "<46"
safari = "<10.1"
ios_saf = "<10.3"
samsung_mob = "<5.0"
