aliases = [ ]
dependencies = [
	"Event",
	"performance.now"
]
docs = "https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserver"
spec = "http://rawgit.com/w3c/IntersectionObserver/master/index.html"
notes = [ ]
repo = "https://github.com/w3c/IntersectionObserver"

[browsers]
android = "*"
bb = "*"
chrome = "<51"
edge = "<16"
edge_mob = "<16"
firefox = "<55"
firefox_mob = "<55"
ie = "*"
ie_mob = "*"
opera = "<45"
op_mob = "<46"
op_mini = "*"
safari = "<17.0" # https://github.com/Financial-Times/polyfill-library/issues/1192#issuecomment-1264367724
ios_saf = "<17.0" # https://github.com/Financial-Times/polyfill-library/issues/1192#issuecomment-1264367724
samsung_mob = "<7.0"
