aliases = [ "css_fq" ]
dependencies = [ ]
license = "MIT"
spec = "https://drafts.csswg.org/css-conditional/#the-css-interface"
docs = "https://developer.mozilla.org/en-US/docs/Web/API/CSS/supports"

[browsers]
android = "<4.4"
chrome = "<28"
firefox = "<22"
firefox_mob = "<22"
ie = "*"
opera = "<15"
op_mini = "*"
safari = "<9.0"
ios_saf = "<9.0"
samsung_mob = "<8.0"
