dependencies = [ "_ArrayIterator", "Symbol.iterator" ]

[browsers]
chrome = "<51"
edge = "<18"
edge_mob = "<18"
firefox = "<13"
firefox_mob = "<14"
ie = "*"
opera = "<38"
op_mob = "<41"
safari = "<11.1"
ios_saf = "<11.0"
samsung_mob = "<5.0"
