aliases = [ "es2022" ]
dependencies = [
	"_ESAbstract.CreateMethodProperty",
	"_ErrorConstructor",
]
spec = "https://tc39.es/ecma262/multipage/fundamental-objects.html#sec-installerrorcause"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause"

[browsers]
android = "*"
bb = "*"
chrome = "<93"
edge = "*"
edge_mob = "*"
firefox = "<91"
firefox_mob = "<91"
ie = "*"
ie_mob = "*"
opera = "<79"
op_mob = "<66"
op_mini = "*"
safari = "<15.0"
ios_saf = "<15.0"
samsung_mob = "<17.0"
