#### Aliases
aliases = []

#### Dependencies
dependencies = [
	"URL"
]

#### Specification Link
spec = "https://url.spec.whatwg.org/#dom-url-tojson"

#### Documentation Link
docs = "https://developer.mozilla.org/en-US/docs/Web/API/URL/toJSON"

#### License
license = "MIT"

#### Browser compatibility
[browsers]
android = "*"
bb = "*"
chrome = "<71"
edge = "<18.17134"
edge_mob = "<17"
firefox = "<54"
firefox_mob = "<54"
ie = ">=9"
ie_mob = ">=9"
opera = "<58"
op_mob = "<50"
op_mini = "<50"
safari = "<12.0"
ios_saf = "<12.0"
samsung_mob = "<10.0"
