aliases = []
dependencies = [ ]
spec = "https://www.w3.org/TR/geometry-1/#DOMRect"
docs = "https://developer.mozilla.org/en-US/docs/Web/API/DOMRect"

[browsers]
android = "*"
chrome = "<61"
edge = "*"
firefox = "<31"
firefox_mob = "<31"
ie = ">=9"
ie_mob = ">=9"
opera = "<48"
op_mob = "<45"
safari = "<10.1"
ios_saf = "<10.3"
samsung_mob = "<8.0"
