dependencies = [
	"Object.getOwnPropertyDescriptor",
]
spec = "https://html.spec.whatwg.org/multipage/dom.html#dom-dataset"
docs = "https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset"

[browsers]
chrome = "<8"
firefox = "<6"
firefox_mob = "<6"
ie = "9 - 10"
opera = "<11"
op_mob = "<11"
safari = "<6.0"
ios_saf = "<6.0"
